# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Routine
version:      v0.70.2
version_from: lib/SQL/Routine.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.6.0
    only:                          0
    Scalar::Util:                  0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
