# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Routine
version:      0.55
version_from: lib/SQL/Routine.pm
installdirs:  site
requires:
    Locale::KeyedText:             1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
